### ISSUE TITLE
Check 2 color sensors on robot

### ISSUE THREAD

**Issue by barel13** [Galaxia5987/robot-2022#40]
Other teams have been having trouble with this we may be having the same problem. Last year through the navx port the signal seemed to be erratic.

**Comment by vichik123** [comment]
It's possible but only with multiplexing or 2 different types of color sensors.

**Comment by katzuv** [comment]
You don't need two color sensors. Cargo can't switch places inside the conveyor, so if you have a color sensor at the bottom of the robot, you'll know what's the color of Cargo in the shooter.
It might require a bit more code, but simplifies the issue here and you have many more options for sensors – beam breakers, proximity sensors, limit switches, etc.

**Comment by vichik123** [comment]
We've decided to use a beam break sensor instead of the color sensor.
