### ISSUE TITLE
Test Swerve 

### ISSUE THREAD

**Issue by adamv17** [Galaxia5987/robot-2022#75]
Add a checklist for checking the swerve.

**Comment by Se-gol** [comment]
---
- [x]  **correct ports for all motors.**

---

- [x]  **update talons firmware.**

---

- [x]  **correct motor inversions for angle motors.**

---

- [x]  **correct motor inversion for drive motors.**

---

- [x]  **reset zero positions for angle motors.**

---

- [x]  **let wheels spin to get rid of all the friction.**

---

- [x]  **tune PID for angle motion magic, as fast as possible until it overshoots.**

---

- [x]  **tune State Space moment of inertia for all wheels so that they reach the desired speed quickly and at the same time.**

---

- [ ]  **test angle encoder slippage.**

---

- [ ]  **make sure the wheels reach their desired angles quickly and relatively at the same time.**

---

- [ ]  **make sure the wheels reach their driving velocities quickly so that they reach it at the same time and that they reach the same velocity.**

---

- [ ]  **make sure navx doesn't blackout when driving hard.**

---

- [ ]  **make sure the wheels drive smoothly on carpet, check for bumps on treads.**

---

- [x]  **make sure resetting the navx angle works fine.**

---

- [x]  **test axes, and field oriented drive.**

---

- [x]  **test odometry readings and autonomous.**

---

- [x]  **confirm it's not that bad with a medium to low battery.**

---

- [ ]  **simulate a real game, 1 navx reset, auto to teleop, stands through collisions.**

---
