### ISSUE TITLE
Test Helicopter Subsystem

### ISSUE THREAD

**Issue by adamv17** [Galaxia5987/robot-2022#76]
Add a checklist for testing the subsystem here.

**Comment by GaiaZano05** [comment]
# Helicopter Test Check- list
## First Priority
- [x] Check the direction of both motors.
- [x] Check what happens when in disable.
- [ ] Check if the stopper is working.
- [ ] Check if the gearbox is slipping.

## Second Priority
- [ ] Find PID velocity constants.
- [ ] Measure the time of the movement.
- [ ] Torque check.





~~It's literally a death machine~~
